/*
 * This file is generated by jOOQ.
 */
package ru.mai.lessons.rpks.jooq.model.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import ru.mai.lessons.rpks.jooq.model.tables.DeduplicationRules;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeduplicationRulesRecord extends UpdatableRecordImpl<DeduplicationRulesRecord> implements Record6<Integer, Long, Long, String, Long, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.deduplication_rules.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.deduplication_rules.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.deduplication_rules.deduplication_id</code>.
     */
    public void setDeduplicationId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.deduplication_rules.deduplication_id</code>.
     */
    public Long getDeduplicationId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.deduplication_rules.rule_id</code>.
     */
    public void setRuleId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.deduplication_rules.rule_id</code>.
     */
    public Long getRuleId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.deduplication_rules.field_name</code>.
     */
    public void setFieldName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.deduplication_rules.field_name</code>.
     */
    public String getFieldName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.deduplication_rules.time_to_live_sec</code>.
     */
    public void setTimeToLiveSec(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.deduplication_rules.time_to_live_sec</code>.
     */
    public Long getTimeToLiveSec() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.deduplication_rules.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.deduplication_rules.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, Long, Long, String, Long, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, Long, Long, String, Long, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return DeduplicationRules.DEDUPLICATION_RULES.ID;
    }

    @Override
    public Field<Long> field2() {
        return DeduplicationRules.DEDUPLICATION_RULES.DEDUPLICATION_ID;
    }

    @Override
    public Field<Long> field3() {
        return DeduplicationRules.DEDUPLICATION_RULES.RULE_ID;
    }

    @Override
    public Field<String> field4() {
        return DeduplicationRules.DEDUPLICATION_RULES.FIELD_NAME;
    }

    @Override
    public Field<Long> field5() {
        return DeduplicationRules.DEDUPLICATION_RULES.TIME_TO_LIVE_SEC;
    }

    @Override
    public Field<Boolean> field6() {
        return DeduplicationRules.DEDUPLICATION_RULES.IS_ACTIVE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getDeduplicationId();
    }

    @Override
    public Long component3() {
        return getRuleId();
    }

    @Override
    public String component4() {
        return getFieldName();
    }

    @Override
    public Long component5() {
        return getTimeToLiveSec();
    }

    @Override
    public Boolean component6() {
        return getIsActive();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getDeduplicationId();
    }

    @Override
    public Long value3() {
        return getRuleId();
    }

    @Override
    public String value4() {
        return getFieldName();
    }

    @Override
    public Long value5() {
        return getTimeToLiveSec();
    }

    @Override
    public Boolean value6() {
        return getIsActive();
    }

    @Override
    public DeduplicationRulesRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public DeduplicationRulesRecord value2(Long value) {
        setDeduplicationId(value);
        return this;
    }

    @Override
    public DeduplicationRulesRecord value3(Long value) {
        setRuleId(value);
        return this;
    }

    @Override
    public DeduplicationRulesRecord value4(String value) {
        setFieldName(value);
        return this;
    }

    @Override
    public DeduplicationRulesRecord value5(Long value) {
        setTimeToLiveSec(value);
        return this;
    }

    @Override
    public DeduplicationRulesRecord value6(Boolean value) {
        setIsActive(value);
        return this;
    }

    @Override
    public DeduplicationRulesRecord values(Integer value1, Long value2, Long value3, String value4, Long value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeduplicationRulesRecord
     */
    public DeduplicationRulesRecord() {
        super(DeduplicationRules.DEDUPLICATION_RULES);
    }

    /**
     * Create a detached, initialised DeduplicationRulesRecord
     */
    public DeduplicationRulesRecord(Integer id, Long deduplicationId, Long ruleId, String fieldName, Long timeToLiveSec, Boolean isActive) {
        super(DeduplicationRules.DEDUPLICATION_RULES);

        setId(id);
        setDeduplicationId(deduplicationId);
        setRuleId(ruleId);
        setFieldName(fieldName);
        setTimeToLiveSec(timeToLiveSec);
        setIsActive(isActive);
    }
}