/*
 * This file is generated by jOOQ.
 */
package ru.mai.lessons.rpks.jooq.model;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import ru.mai.lessons.rpks.jooq.model.tables.DeduplicationRules;
import ru.mai.lessons.rpks.jooq.model.tables.records.DeduplicationRulesRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<DeduplicationRulesRecord> DEDUPLICATION_RULES_PKEY = Internal.createUniqueKey(DeduplicationRules.DEDUPLICATION_RULES, DSL.name("deduplication_rules_pkey"), new TableField[] { DeduplicationRules.DEDUPLICATION_RULES.ID }, true);
}