/*
 * This file is generated by jOOQ.
 */
package ru.mai.lessons.rpks.jooq;


import ru.mai.lessons.rpks.jooq.tables.DeduplicationRules;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.deduplication_rules</code>.
     */
    public static final DeduplicationRules DEDUPLICATION_RULES = DeduplicationRules.DEDUPLICATION_RULES;
}
